spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5433/postgres?schema=anime
    username: root
    password: root

logging:
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG

server:
  error:
    include-stacktrace: on_param